name: drugcoach
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  url_launcher: ^6.1.2
  firebase_database: ^9.0.15
  cupertino_icons: ^1.0.2
  firebase_core: ^1.17.0
  firebase_auth: ^3.3.18
  shared_preferences: ^2.0.15
  dcdg: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true


  assets:
     - assets/
     - assets/lang/


  fonts:
    - family: Oswald
      fonts:
        - asset: assets/Fonts/Oswald/static/Oswald-Medium.ttf
